### ISSUE TITLE
bug: too long filename

### ISSUE THREAD

**Issue by davidsneighbour** [CloudCannon/flatlake#9]
Running flatlake on [my repo](https://github.com/davidsneighbour/kollitsch.dev) with flatlake.yaml:

```yaml
collections:
  - output_key: posts
    inputs:
      - path: content/blog
  - output_key: tags
    inputs:
      - path: content/tags
```

Results in an error about a too long filename without much more information:

```
[14:46:53][patrick@gugin][main]~/github.com/davidsneighbour/kollitsch.dev(+1|%0|!101)
❯ RUST_BACKTRACE=1 npx -y flatlake
flatlake running as 0.4.3

[Walking collections]
thread 'main' panicked at /home/runner/work/flatlake/flatlake/flatlake/src/outflow/mod.rs:142:38:
called `Result::unwrap()` on an `Err` value: Os { code: 36, kind: InvalidFilename, message: "Filename too long" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: flatlake::outflow::write::{{closure}}
   4: <futures_util::stream::futures_ordered::OrderWrapper<T> as core::future::future::Future>::poll
   5: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   6: <futures_util::stream::futures_ordered::FuturesOrdered<Fut> as futures_core::stream::Stream>::poll_next
   7: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
   8: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll
   9: tokio::runtime::park::CachedParkThread::block_on
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::runtime::Runtime::block_on
  12: flatlake::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[14:49:02][patrick@gugin][main]~/github.com/davidsneighbour/kollitsch.dev(+1|%0|!101)
❯ 
```

I would expect two things:

- less panic and some workaround to make the filename shorter internally
- some info about what content file caused this issue

**Comment by davidsneighbour** [comment]
A folder `api` is created, but only filled up to a certain point and with many empty folders.
